# SVD
## 公式
$Data_{m\times n} = U_{m \times m} \sum_{m \times n} V_{n \times n}^T$

In [1]:
import numpy as np

In [3]:
def load_dataset():
    return[[0, 0, 0, 2, 2],
           [0, 0, 0, 3, 3],
           [0, 0, 0, 1, 1],
           [1, 1, 1, 0, 0],
           [2, 2, 2, 0, 0],
           [5, 5, 5, 0, 0],
           [1, 1, 1, 0, 0]]

In [4]:
dataset = load_dataset()

In [5]:
dataset

[[0, 0, 0, 2, 2],
 [0, 0, 0, 3, 3],
 [0, 0, 0, 1, 1],
 [1, 1, 1, 0, 0],
 [2, 2, 2, 0, 0],
 [5, 5, 5, 0, 0],
 [1, 1, 1, 0, 0]]

## 示意图
![svd-dispose](svd-dispose.png)

In [6]:
u, sigma, vt = np.linalg.svd(dataset)

In [7]:
u

array([[ -2.22044605e-16,   5.34522484e-01,   8.41650989e-01,
          5.59998398e-02,  -5.26625636e-02,   2.77555756e-17,
          1.38777878e-17],
       [  0.00000000e+00,   8.01783726e-01,  -4.76944344e-01,
         -2.09235996e-01,   2.93065263e-01,  -4.01696905e-17,
         -2.77555756e-17],
       [  0.00000000e+00,   2.67261242e-01,  -2.52468946e-01,
          5.15708308e-01,  -7.73870662e-01,   1.54770403e-16,
          0.00000000e+00],
       [ -1.79605302e-01,   0.00000000e+00,   7.39748546e-03,
         -3.03901436e-01,  -2.04933639e-01,   8.94308074e-01,
         -1.83156768e-01],
       [ -3.59210604e-01,   0.00000000e+00,   1.47949709e-02,
         -6.07802873e-01,  -4.09867278e-01,  -4.47451355e-01,
         -3.64856984e-01],
       [ -8.98026510e-01,   0.00000000e+00,  -8.87698255e-03,
          3.64681724e-01,   2.45920367e-01,  -1.07974660e-16,
         -1.12074131e-17],
       [ -1.79605302e-01,   0.00000000e+00,   7.39748546e-03,
         -3.03901436e-01,  -2.04

In [8]:
sigma

array([  9.64365076e+00,   5.29150262e+00,   7.40623935e-16,
         4.05103551e-16,   2.21838243e-32])

In [9]:
vt

array([[ -5.77350269e-01,  -5.77350269e-01,  -5.77350269e-01,
          0.00000000e+00,   0.00000000e+00],
       [ -2.46566547e-16,   1.23283273e-16,   1.23283273e-16,
          7.07106781e-01,   7.07106781e-01],
       [ -7.83779232e-01,   5.90050124e-01,   1.93729108e-01,
         -2.77555756e-16,  -2.22044605e-16],
       [ -2.28816045e-01,  -5.64364703e-01,   7.93180748e-01,
          1.11022302e-16,  -1.11022302e-16],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         -7.07106781e-01,   7.07106781e-01]])

### 选择奇异值
有很多启发式算法，既可以单纯的选择最大的n个，也可以按照能量信息来（选择平方和占比90%的奇异值）。