# 朴素贝叶斯分类器
## 使用Python进行文本分类
对于网上留言，我们使用Python来鉴别它是否是侮辱性言论。

In [1]:
def load_dataset():
    """
    创建了一些实验样本
    """
    dataset=[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'], 
             ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'], 
             ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'], 
             ['stop', 'posting', 'stupid', 'worthless', 'garbage'], 
             ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'], 
             ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]
    classes = [0, 1, 0, 1, 0, 1]  #1 is abusive(骂人的，滥用的), 0 not
    return dataset, classes

In [2]:
def create_vocabulary(dataset):
    """
    创建一个包含在所有文档中出现的不重复词的列表
    """
    vocabulary = set()
    for sample in dataset:
        for s in sample:
            vocabulary.add(s)
    return list(vocabulary)

In [3]:
import numpy as np

In [4]:
def vectorization(vocabulary, sample):
    """
    返回文本向量，0表示单词未出现，1表示出现
    """
    vector = np.zeros(len(vocabulary))
    for s in sample:
        if s in vocabulary:
            vector[vocabulary.index(s)] = 1  # 也可以是`+= 1` 表示出现次数
        else: print("the word: %s is not in my Vocabulary!" % s)
    return vector

In [5]:
dataset, classes = load_dataset()

In [6]:
dataset

[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
 ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
 ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]

In [7]:
classes

[0, 1, 0, 1, 0, 1]

In [8]:
vocabulary = create_vocabulary(dataset)
print(vocabulary)

['buying', 'worthless', 'dog', 'ate', 'love', 'park', 'to', 'maybe', 'how', 'please', 'flea', 'my', 'has', 'help', 'is', 'quit', 'food', 'cute', 'stop', 'posting', 'so', 'not', 'mr', 'dalmation', 'problems', 'take', 'licks', 'stupid', 'garbage', 'I', 'steak', 'him']


In [9]:
print(vectorization(vocabulary, dataset[0]))

[ 0.  0.  1.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]


$$p(c_i | w) = \frac{p(w|c_i)p(c_i)}{p(w)}$$
其中，$w$表示文本向量，$c_i$表示分类结果

### 朴素贝叶斯分类器算法
```
计算每个类别中的文本的数目
对每篇训练文档：
    对每个类别：
        如果词条出现在文档中=>增加该词条的计数值
        增加所有词条的计数值
    对每个类别：
        对每个词条：
            将该词条的数目除以总词条的数目得到条件概率
    返回每个类别的条件概率
```

In [10]:
def train(dataset, classes):
    n_sample = len(dataset)
    n_word = len(dataset[0])
    p_abusive = sum(classes) / float(n_sample)
    # 防止0有些单词的条件概率为0，导致相乘后的结果等于0
    p0_word = np.ones(n_word)
    p1_word = np.ones(n_word)
    p0_sum = 2.0
    p1_sum = 2.0
    for i in range(n_sample):
        if classes[i] == 1:
            p1_word += dataset[i]
            p1_sum += sum(dataset[i])
        else:
            p0_word += dataset[i]
            p0_sum += sum(dataset[i])
    # change to log()
    p1_vector = np.log(p1_word / p1_sum)
    p0_vector = np.log(p0_word / p0_sum)
    return p0_vector, p1_vector, p_abusive

In [11]:
vectorized_dataset = []
for sample in dataset:
    vectorized_dataset.append(vectorization(vocabulary, sample))

In [12]:
vectorized_dataset

[array([ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,
         1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.]),
 array([ 0.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,
         0.,  1.,  0.,  0.,  0.,  1.]),
 array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,
         0.,  0.,  0.,  1.,  0.,  1.]),
 array([ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  1.,  1.,  0.,  0.,  0.]),
 array([ 0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
         1.,  0.,  0.,  0.,  1.,  1.]),
 array([ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [13]:
p0_v, p1_v, p_ab = train(vectorized_dataset, classes)

In [14]:
p0_v, p1_v, p_ab

(array([-3.25809654, -3.25809654, -2.56494936, -2.56494936, -2.56494936,
        -3.25809654, -2.56494936, -3.25809654, -2.56494936, -2.56494936,
        -2.56494936, -1.87180218, -2.56494936, -2.56494936, -2.56494936,
        -3.25809654, -3.25809654, -2.56494936, -2.56494936, -3.25809654,
        -2.56494936, -3.25809654, -2.56494936, -2.56494936, -2.56494936,
        -3.25809654, -2.56494936, -3.25809654, -3.25809654, -2.56494936,
        -2.56494936, -2.15948425]),
 array([-2.35137526, -1.94591015, -1.94591015, -3.04452244, -3.04452244,
        -2.35137526, -2.35137526, -2.35137526, -3.04452244, -3.04452244,
        -3.04452244, -3.04452244, -3.04452244, -3.04452244, -3.04452244,
        -2.35137526, -2.35137526, -3.04452244, -2.35137526, -2.35137526,
        -3.04452244, -2.35137526, -3.04452244, -3.04452244, -3.04452244,
        -2.35137526, -3.04452244, -1.65822808, -2.35137526, -3.04452244,
        -3.04452244, -2.35137526]),
 0.5)

In [15]:
def classification(sample, p0_v, p1_v, p_ab):
    p1 = sum(sample * p1_v) + np.log(p_ab)
    p0 = sum(sample * p0_v) + np.log(1.0 - p_ab)
    return int(p1 > p0)

In [16]:
def test():
    dataset, classes = load_dataset()
    vocabulary = create_vocabulary(dataset)
    samples = []
    for sample in dataset:
        samples.append(vectorization(vocabulary, sample))
    p0_v, p1_1, p_ab = train(np.array(samples), np.array(classes))
    test_sample = ['love', 'my', 'dalmation']
    test_sample = np.array(vectorization(vocabulary, test_sample))
    print('=>', classification(test_sample, p0_v, p1_v, p_ab))
    test_sample = ['stupid', 'garbage']
    test_sample = np.array(vectorization(vocabulary, test_sample))
    print('=>', classification(test_sample, p0_v, p1_v, p_ab))

In [17]:
test()

=> 0
=> 1
