# 线性回归

In [1]:
import numpy as np

In [2]:
def load_dataset(file_name):
	"""general function to parse tab-delimited floats"""
	n_features = 8
	dataset = []
	labels = []
	f = open(file_name)
	for line in f.readlines():
		sample = []
		line_list = line.strip().split('\t')
		for i in range(n_features):
			sample.append(float(line_list[i]))
		dataset.append(sample)
		labels.append(float(line_list[-1]))
	f.close()
	return dataset, labels

In [3]:
def calc_error(y_true, y_pred):
	"""yArr and yHatArr both need to be arrays"""
	return ((y_true - y_pred) ** 2).sum()

In [4]:
def regularize(x_matrix):
	"""regularize by columns"""
	rs_matrix = x_matrix.copy()
	rs_mean = np.mean(rs_matrix, 0)  # calc mean then subtract it off
	rs_variance = np.var(rs_matrix, 0)  # calc variance of Xi then divide by it
	rs_matrix = (rs_matrix - rs_mean) / rs_variance
	return rs_matrix

In [5]:
def train(dataset, labels, lr=0.01, epochs=100):
	x_matrix = np.mat(dataset)
	y_matrix = np.mat(labels).T
	y_mean = np.mean(y_matrix, 0)
	y_matrix = y_matrix - y_mean  # can also regularize ys but will get smaller coef
	x_matrix = regularize(x_matrix)
	n_features = x_matrix.shape[1]
	result = np.zeros((epochs, n_features))  # testing code remove
	ws = np.zeros((n_features, 1))
	w_best = ws.copy()
	for i in range(epochs):
		print(ws.T)
		min_error = np.inf
		for j in range(n_features):
			for sign in [-1, 1]:
				w_cur = ws.copy()
				w_cur[j] += lr * sign
				y_test = x_matrix * w_cur
				errpr = calc_error(y_matrix.A, y_test.A)
				if errpr < min_error:
					min_error = errpr
					w_best = w_cur
		ws = w_best.copy()
		result[i, :] = ws.T
	return result

In [6]:
dataset, labels = load_dataset('linear-dataset.txt')

In [7]:
dataset

[[1.0, 0.455, 0.365, 0.095, 0.514, 0.2245, 0.101, 0.15],
 [1.0, 0.35, 0.265, 0.09, 0.2255, 0.0995, 0.0485, 0.07],
 [-1.0, 0.53, 0.42, 0.135, 0.677, 0.2565, 0.1415, 0.21],
 [1.0, 0.44, 0.365, 0.125, 0.516, 0.2155, 0.114, 0.155],
 [0.0, 0.33, 0.255, 0.08, 0.205, 0.0895, 0.0395, 0.055],
 [0.0, 0.425, 0.3, 0.095, 0.3515, 0.141, 0.0775, 0.12],
 [-1.0, 0.53, 0.415, 0.15, 0.7775, 0.237, 0.1415, 0.33],
 [-1.0, 0.545, 0.425, 0.125, 0.768, 0.294, 0.1495, 0.26],
 [1.0, 0.475, 0.37, 0.125, 0.5095, 0.2165, 0.1125, 0.165],
 [-1.0, 0.55, 0.44, 0.15, 0.8945, 0.3145, 0.151, 0.32],
 [-1.0, 0.525, 0.38, 0.14, 0.6065, 0.194, 0.1475, 0.21],
 [1.0, 0.43, 0.35, 0.11, 0.406, 0.1675, 0.081, 0.135],
 [1.0, 0.49, 0.38, 0.135, 0.5415, 0.2175, 0.095, 0.19],
 [-1.0, 0.535, 0.405, 0.145, 0.6845, 0.2725, 0.171, 0.205],
 [-1.0, 0.47, 0.355, 0.1, 0.4755, 0.1675, 0.0805, 0.185],
 [1.0, 0.5, 0.4, 0.13, 0.6645, 0.258, 0.133, 0.24],
 [0.0, 0.355, 0.28, 0.085, 0.2905, 0.095, 0.0395, 0.115],
 [-1.0, 0.44, 0.34, 0.1, 0.451, 0

In [8]:
print(labels)

[15.0, 7.0, 9.0, 10.0, 7.0, 8.0, 20.0, 16.0, 9.0, 19.0, 14.0, 10.0, 11.0, 10.0, 10.0, 12.0, 7.0, 10.0, 7.0, 9.0, 11.0, 10.0, 12.0, 9.0, 10.0, 11.0, 11.0, 12.0, 15.0, 11.0, 10.0, 15.0, 18.0, 19.0, 13.0, 8.0, 16.0, 8.0, 11.0, 9.0, 9.0, 14.0, 5.0, 5.0, 4.0, 7.0, 9.0, 7.0, 6.0, 9.0, 8.0, 7.0, 10.0, 10.0, 7.0, 8.0, 8.0, 8.0, 4.0, 7.0, 7.0, 9.0, 10.0, 7.0, 8.0, 8.0, 12.0, 13.0, 10.0, 6.0, 13.0, 8.0, 20.0, 11.0, 13.0, 15.0, 9.0, 10.0, 11.0, 14.0, 9.0, 12.0, 16.0, 21.0, 14.0, 12.0, 13.0, 10.0, 9.0, 12.0, 15.0, 12.0, 13.0, 10.0, 15.0, 14.0, 9.0, 8.0, 7.0, 10.0, 7.0, 15.0, 15.0, 10.0, 12.0, 12.0, 11.0, 10.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 11.0, 11.0, 11.0, 10.0, 9.0, 8.0, 9.0, 7.0, 14.0, 6.0, 6.0, 5.0, 6.0, 8.0, 19.0, 18.0, 17.0, 9.0, 7.0, 7.0, 7.0, 8.0, 7.0, 9.0, 9.0, 9.0, 10.0, 10.0, 16.0, 11.0, 10.0, 10.0, 10.0, 9.0, 5.0, 4.0, 15.0, 9.0, 10.0, 10.0, 12.0, 10.0, 13.0, 16.0, 13.0, 13.0, 13.0, 13.0, 12.0, 18.0, 16.0, 14.0, 20.0, 20.0, 14.0, 12.0, 14.0, 7.0, 8.0, 8.0, 5.0, 7.0, 5.0, 8.0, 4.0, 11.0

In [9]:
train(dataset, labels, 0.001, 5000)

[[ 0.  0.  0.  0.  0.  0.  0.  0.]]
[[ 0.     0.     0.     0.001  0.     0.     0.     0.   ]]
[[ 0.     0.     0.     0.002  0.     0.     0.     0.   ]]
[[ 0.     0.     0.     0.003  0.     0.     0.     0.   ]]
[[ 0.     0.     0.     0.004  0.     0.     0.     0.   ]]
[[ 0.     0.     0.     0.005  0.     0.     0.     0.   ]]
[[ 0.     0.     0.     0.006  0.     0.     0.     0.   ]]
[[ 0.     0.     0.     0.007  0.     0.     0.     0.   ]]
[[ 0.     0.     0.     0.008  0.     0.     0.     0.   ]]
[[ 0.     0.     0.     0.009  0.     0.     0.     0.   ]]
[[ 0.    0.    0.    0.01  0.    0.    0.    0.  ]]
[[ 0.     0.     0.     0.011  0.     0.     0.     0.   ]]
[[ 0.     0.     0.     0.012  0.     0.     0.     0.   ]]
[[ 0.     0.     0.     0.013  0.     0.     0.     0.   ]]
[[ 0.     0.     0.     0.014  0.     0.     0.     0.   ]]
[[ 0.     0.     0.     0.015  0.     0.     0.     0.   ]]
[[ 0.     0.     0.     0.016  0.     0.     0.     0.   ]]
[[ 0.     0.

[[ 0.     0.     0.005  0.054  0.     0.     0.     0.093]]
[[ 0.     0.     0.005  0.054  0.     0.     0.     0.094]]
[[ 0.     0.     0.005  0.053  0.     0.     0.     0.094]]
[[ 0.     0.     0.005  0.053  0.     0.     0.     0.095]]
[[ 0.     0.     0.005  0.053  0.     0.     0.     0.096]]
[[ 0.     0.     0.005  0.053  0.     0.     0.     0.097]]
[[ 0.     0.     0.005  0.053  0.     0.     0.     0.098]]
[[ 0.     0.     0.005  0.052  0.     0.     0.     0.098]]
[[ 0.     0.     0.005  0.052  0.     0.     0.     0.099]]
[[ 0.     0.     0.005  0.052  0.     0.     0.     0.1  ]]
[[ 0.     0.     0.005  0.052  0.     0.     0.     0.101]]
[[ 0.     0.     0.005  0.052  0.     0.     0.     0.102]]
[[ 0.     0.     0.005  0.051  0.     0.     0.     0.102]]
[[ 0.     0.     0.005  0.051  0.     0.     0.     0.103]]
[[ 0.     0.     0.005  0.051  0.     0.     0.     0.104]]
[[ 0.     0.     0.005  0.051  0.     0.     0.     0.105]]
[[ 0.     0.     0.005  0.05   0.     0.

[[ 0.     0.     0.005  0.044  0.    -0.084  0.     0.18 ]]
[[ 0.     0.     0.005  0.044  0.    -0.085  0.     0.18 ]]
[[ 0.     0.     0.005  0.044  0.    -0.086  0.     0.18 ]]
[[ 0.     0.     0.005  0.044  0.    -0.086  0.     0.181]]
[[ 0.     0.     0.005  0.044  0.    -0.087  0.     0.181]]
[[ 0.     0.     0.005  0.044  0.    -0.088  0.     0.181]]
[[ 0.     0.     0.005  0.044  0.    -0.088  0.     0.182]]
[[ 0.     0.     0.005  0.044  0.    -0.089  0.     0.182]]
[[ 0.     0.     0.005  0.044  0.    -0.089  0.     0.183]]
[[ 0.     0.     0.005  0.044  0.    -0.09   0.     0.183]]
[[ 0.     0.     0.005  0.044  0.    -0.091  0.     0.183]]
[[ 0.     0.     0.005  0.044  0.    -0.091  0.     0.184]]
[[ 0.     0.     0.005  0.044  0.    -0.092  0.     0.184]]
[[ 0.     0.     0.005  0.044  0.    -0.093  0.     0.184]]
[[ 0.     0.     0.005  0.044  0.    -0.093  0.     0.185]]
[[ 0.     0.     0.005  0.044  0.    -0.094  0.     0.185]]
[[ 0.     0.     0.005  0.044  0.    -0.

[[ 0.     0.     0.02   0.04   0.    -0.195  0.     0.238]]
[[ 0.     0.     0.02   0.04   0.    -0.195  0.     0.239]]
[[ 0.     0.     0.02   0.039  0.    -0.195  0.     0.239]]
[[ 0.     0.     0.021  0.039  0.    -0.195  0.     0.239]]
[[ 0.     0.     0.022  0.039  0.    -0.195  0.     0.239]]
[[ 0.     0.     0.022  0.039  0.    -0.196  0.     0.239]]
[[ 0.     0.     0.022  0.039  0.    -0.197  0.     0.239]]
[[ 0.     0.     0.022  0.039  0.    -0.197  0.     0.24 ]]
[[ 0.     0.     0.022  0.039  0.    -0.198  0.     0.24 ]]
[[ 0.     0.     0.022  0.039  0.    -0.199  0.     0.24 ]]
[[ 0.     0.     0.022  0.039  0.    -0.199  0.     0.241]]
[[ 0.     0.     0.022  0.039  0.    -0.2    0.     0.241]]
[[ 0.     0.     0.022  0.039  0.    -0.2    0.     0.242]]
[[ 0.     0.     0.022  0.039  0.    -0.201  0.     0.242]]
[[ 0.     0.     0.022  0.039  0.    -0.202  0.     0.242]]
[[ 0.     0.     0.023  0.039  0.    -0.202  0.     0.242]]
[[ 0.     0.     0.023  0.039  0.    -0.

[[ 0.     0.     0.049  0.035  0.    -0.306  0.     0.282]]
[[ 0.     0.     0.049  0.034  0.    -0.306  0.     0.282]]
[[ 0.     0.     0.05   0.034  0.    -0.306  0.     0.282]]
[[ 0.     0.     0.05   0.034  0.    -0.306  0.     0.283]]
[[ 0.     0.     0.05   0.034  0.    -0.307  0.     0.283]]
[[ 0.     0.     0.05   0.034  0.    -0.307  0.     0.284]]
[[ 0.     0.     0.05   0.034  0.    -0.308  0.     0.284]]
[[ 0.     0.     0.05   0.034  0.    -0.309  0.     0.284]]
[[ 0.     0.     0.05   0.034  0.    -0.309  0.     0.285]]
[[ 0.     0.     0.05   0.034  0.    -0.31   0.     0.285]]
[[ 0.     0.     0.05   0.034  0.    -0.31   0.     0.286]]
[[ 0.     0.     0.05   0.034  0.    -0.311  0.     0.286]]
[[ 0.     0.     0.05   0.034  0.    -0.312  0.     0.286]]
[[ 0.     0.     0.051  0.034  0.    -0.312  0.     0.286]]
[[ 0.     0.     0.051  0.034  0.    -0.313  0.     0.286]]
[[ 0.     0.     0.051  0.034  0.    -0.314  0.     0.286]]
[[ 0.     0.     0.051  0.034  0.    -0.

[[ 0.     0.     0.077  0.029  0.    -0.412  0.     0.326]]
[[ 0.     0.     0.077  0.029  0.    -0.413  0.     0.326]]
[[ 0.     0.     0.077  0.029  0.    -0.413  0.     0.327]]
[[ 0.     0.     0.077  0.029  0.    -0.414  0.     0.327]]
[[ 0.     0.     0.077  0.029  0.    -0.415  0.     0.327]]
[[ 0.     0.     0.078  0.029  0.    -0.415  0.     0.327]]
[[ 0.     0.     0.078  0.029  0.    -0.416  0.     0.327]]
[[ 0.     0.     0.078  0.029  0.    -0.417  0.     0.327]]
[[ 0.     0.     0.078  0.029  0.    -0.417  0.     0.328]]
[[ 0.     0.     0.078  0.029  0.    -0.418  0.     0.328]]
[[ 0.     0.     0.078  0.029  0.    -0.419  0.     0.328]]
[[ 0.     0.     0.078  0.029  0.    -0.419  0.     0.329]]
[[ 0.     0.     0.078  0.029  0.    -0.42   0.     0.329]]
[[ 0.     0.     0.078  0.029  0.    -0.42   0.     0.33 ]]
[[ 0.     0.     0.078  0.029  0.    -0.421  0.     0.33 ]]
[[ 0.     0.     0.078  0.029  0.    -0.422  0.     0.33 ]]
[[ 0.     0.     0.079  0.029  0.    -0.

[[ 0.     0.     0.103  0.025  0.    -0.518  0.     0.368]]
[[ 0.     0.     0.103  0.024  0.    -0.518  0.     0.368]]
[[ 0.     0.     0.104  0.024  0.    -0.518  0.     0.368]]
[[ 0.     0.     0.104  0.024  0.    -0.518  0.     0.369]]
[[ 0.     0.     0.104  0.024  0.    -0.519  0.     0.369]]
[[ 0.     0.     0.104  0.024  0.    -0.519  0.     0.37 ]]
[[ 0.     0.     0.104  0.024  0.    -0.52   0.     0.37 ]]
[[ 0.     0.     0.104  0.024  0.    -0.521  0.     0.37 ]]
[[ 0.     0.     0.105  0.024  0.    -0.521  0.     0.37 ]]
[[ 0.     0.     0.105  0.024  0.    -0.522  0.     0.37 ]]
[[ 0.     0.     0.105  0.024  0.    -0.523  0.     0.37 ]]
[[ 0.     0.     0.105  0.024  0.    -0.523  0.     0.371]]
[[ 0.     0.     0.105  0.024  0.    -0.524  0.     0.371]]
[[ 0.     0.     0.105  0.024  0.    -0.525  0.     0.371]]
[[ 0.     0.     0.105  0.024  0.    -0.525  0.     0.372]]
[[ 0.     0.     0.105  0.024  0.    -0.526  0.     0.372]]
[[ 0.     0.     0.105  0.024  0.    -0.

[[ 0.001  0.     0.109  0.023  0.11  -0.579 -0.002  0.374]]
[[ 0.001  0.     0.109  0.023  0.111 -0.579 -0.002  0.374]]
[[ 0.001  0.     0.109  0.023  0.111 -0.579 -0.003  0.374]]
[[ 0.001  0.     0.109  0.023  0.112 -0.579 -0.003  0.374]]
[[ 0.001  0.     0.109  0.023  0.113 -0.579 -0.003  0.374]]
[[ 0.001  0.     0.109  0.023  0.114 -0.579 -0.003  0.374]]
[[ 0.001  0.     0.109  0.023  0.115 -0.579 -0.003  0.374]]
[[ 0.001  0.     0.109  0.023  0.115 -0.58  -0.003  0.374]]
[[ 0.001  0.     0.109  0.023  0.116 -0.58  -0.003  0.374]]
[[ 0.001  0.     0.109  0.023  0.117 -0.58  -0.003  0.374]]
[[ 0.001  0.     0.109  0.023  0.118 -0.58  -0.003  0.374]]
[[ 0.001  0.     0.109  0.022  0.118 -0.58  -0.003  0.374]]
[[ 0.001  0.     0.11   0.022  0.118 -0.58  -0.003  0.374]]
[[ 0.001  0.     0.11   0.022  0.119 -0.58  -0.003  0.374]]
[[ 0.001  0.     0.11   0.022  0.12  -0.58  -0.003  0.374]]
[[ 0.001  0.     0.11   0.022  0.121 -0.58  -0.003  0.374]]
[[ 0.001  0.     0.11   0.022  0.122 -0.

[[ 0.006  0.     0.11   0.022  0.24  -0.609 -0.011  0.368]]
[[ 0.006  0.     0.11   0.022  0.241 -0.609 -0.011  0.368]]
[[ 0.006  0.     0.11   0.022  0.241 -0.609 -0.011  0.367]]
[[ 0.006  0.     0.11   0.022  0.242 -0.609 -0.011  0.367]]
[[ 0.006  0.     0.11   0.022  0.243 -0.609 -0.011  0.367]]
[[ 0.006  0.     0.11   0.022  0.244 -0.609 -0.011  0.367]]
[[ 0.006  0.     0.11   0.022  0.245 -0.609 -0.011  0.367]]
[[ 0.006  0.     0.11   0.022  0.245 -0.609 -0.012  0.367]]
[[ 0.006  0.     0.11   0.022  0.246 -0.609 -0.012  0.367]]
[[ 0.006  0.     0.11   0.022  0.247 -0.609 -0.012  0.367]]
[[ 0.006  0.     0.11   0.022  0.248 -0.609 -0.012  0.367]]
[[ 0.006  0.     0.11   0.022  0.249 -0.609 -0.012  0.367]]
[[ 0.006  0.     0.11   0.022  0.249 -0.61  -0.012  0.367]]
[[ 0.006  0.     0.11   0.022  0.25  -0.61  -0.012  0.367]]
[[ 0.006  0.     0.11   0.022  0.251 -0.61  -0.012  0.367]]
[[ 0.006  0.     0.11   0.022  0.251 -0.611 -0.012  0.367]]
[[ 0.006  0.     0.11   0.022  0.252 -0.

[[ 0.009  0.     0.11   0.022  0.376 -0.634 -0.019  0.354]]
[[ 0.009  0.     0.11   0.022  0.377 -0.634 -0.019  0.354]]
[[ 0.009  0.     0.11   0.022  0.377 -0.635 -0.019  0.354]]
[[ 0.009  0.     0.11   0.022  0.378 -0.635 -0.019  0.354]]
[[ 0.009  0.     0.11   0.022  0.379 -0.635 -0.019  0.354]]
[[ 0.009  0.     0.11   0.022  0.38  -0.635 -0.019  0.354]]
[[ 0.009  0.     0.11   0.022  0.38  -0.636 -0.019  0.354]]
[[ 0.009  0.     0.11   0.022  0.381 -0.636 -0.019  0.354]]
[[ 0.009  0.     0.11   0.022  0.382 -0.636 -0.019  0.354]]
[[ 0.009  0.     0.11   0.022  0.382 -0.636 -0.019  0.353]]
[[ 0.009  0.     0.11   0.022  0.383 -0.636 -0.019  0.353]]
[[ 0.009  0.     0.11   0.022  0.384 -0.636 -0.019  0.353]]
[[ 0.009  0.     0.11   0.022  0.385 -0.636 -0.019  0.353]]
[[ 0.009  0.     0.11   0.022  0.385 -0.637 -0.019  0.353]]
[[ 0.009  0.     0.11   0.022  0.386 -0.637 -0.019  0.353]]
[[ 0.009  0.     0.11   0.022  0.387 -0.637 -0.019  0.353]]
[[ 0.009  0.     0.11   0.022  0.387 -0.

[[ 0.012  0.     0.11   0.022  0.51  -0.662 -0.026  0.341]]
[[ 0.012  0.     0.11   0.022  0.511 -0.662 -0.026  0.341]]
[[ 0.012  0.     0.11   0.022  0.512 -0.662 -0.026  0.341]]
[[ 0.012  0.     0.11   0.022  0.512 -0.663 -0.026  0.341]]
[[ 0.012  0.     0.11   0.022  0.513 -0.663 -0.026  0.341]]
[[ 0.012  0.     0.11   0.022  0.514 -0.663 -0.026  0.341]]
[[ 0.012  0.     0.11   0.022  0.515 -0.663 -0.026  0.341]]
[[ 0.012  0.     0.11   0.022  0.515 -0.663 -0.026  0.34 ]]
[[ 0.012  0.     0.11   0.022  0.516 -0.663 -0.026  0.34 ]]
[[ 0.012  0.     0.11   0.022  0.517 -0.663 -0.026  0.34 ]]
[[ 0.012  0.     0.11   0.022  0.518 -0.663 -0.026  0.34 ]]
[[ 0.012  0.     0.11   0.022  0.518 -0.664 -0.026  0.34 ]]
[[ 0.012  0.     0.11   0.022  0.519 -0.664 -0.026  0.34 ]]
[[ 0.012  0.     0.11   0.022  0.52  -0.664 -0.026  0.34 ]]
[[ 0.012  0.     0.11   0.022  0.52  -0.664 -0.026  0.339]]
[[ 0.012  0.     0.11   0.022  0.521 -0.664 -0.026  0.339]]
[[ 0.012  0.     0.11   0.022  0.522 -0.

[[ 0.015  0.     0.11   0.022  0.645 -0.688 -0.033  0.327]]
[[ 0.015  0.     0.11   0.022  0.646 -0.688 -0.033  0.327]]
[[ 0.015  0.     0.11   0.022  0.646 -0.689 -0.033  0.327]]
[[ 0.015  0.     0.11   0.022  0.647 -0.689 -0.033  0.327]]
[[ 0.015  0.     0.11   0.022  0.648 -0.689 -0.033  0.327]]
[[ 0.015  0.     0.11   0.022  0.649 -0.689 -0.033  0.327]]
[[ 0.015  0.     0.11   0.022  0.649 -0.689 -0.033  0.326]]
[[ 0.015  0.     0.11   0.022  0.65  -0.689 -0.033  0.326]]
[[ 0.015  0.     0.11   0.022  0.651 -0.689 -0.033  0.326]]
[[ 0.015  0.     0.11   0.022  0.652 -0.689 -0.033  0.326]]
[[ 0.015  0.     0.11   0.022  0.652 -0.69  -0.033  0.326]]
[[ 0.015  0.     0.11   0.022  0.653 -0.69  -0.033  0.326]]
[[ 0.015  0.     0.11   0.022  0.654 -0.69  -0.033  0.326]]
[[ 0.015  0.     0.11   0.022  0.654 -0.691 -0.033  0.326]]
[[ 0.015  0.     0.11   0.022  0.655 -0.691 -0.033  0.326]]
[[ 0.015  0.     0.11   0.022  0.656 -0.691 -0.033  0.326]]
[[ 0.015  0.     0.11   0.022  0.656 -0.

[[ 0.017  0.     0.11   0.022  0.781 -0.716 -0.04   0.313]]
[[ 0.017  0.     0.11   0.022  0.782 -0.716 -0.04   0.313]]
[[ 0.017  0.     0.11   0.022  0.783 -0.716 -0.04   0.313]]
[[ 0.017  0.     0.11   0.022  0.784 -0.716 -0.04   0.313]]
[[ 0.017  0.     0.11   0.022  0.785 -0.716 -0.04   0.313]]
[[ 0.017  0.     0.11   0.022  0.785 -0.716 -0.041  0.313]]
[[ 0.017  0.     0.11   0.022  0.786 -0.716 -0.041  0.313]]
[[ 0.017  0.     0.11   0.022  0.787 -0.716 -0.041  0.313]]
[[ 0.017  0.     0.11   0.022  0.788 -0.716 -0.041  0.313]]
[[ 0.017  0.     0.11   0.022  0.789 -0.716 -0.041  0.313]]
[[ 0.017  0.     0.11   0.022  0.789 -0.717 -0.041  0.313]]
[[ 0.017  0.     0.11   0.022  0.79  -0.717 -0.041  0.313]]
[[ 0.017  0.     0.11   0.022  0.791 -0.717 -0.041  0.313]]
[[ 0.017  0.     0.11   0.022  0.791 -0.717 -0.041  0.312]]
[[ 0.017  0.     0.11   0.022  0.792 -0.717 -0.041  0.312]]
[[ 0.017  0.     0.11   0.022  0.793 -0.717 -0.041  0.312]]
[[ 0.017  0.     0.11   0.022  0.794 -0.

[[ 0.02   0.     0.11   0.022  0.917 -0.743 -0.047  0.3  ]]
[[ 0.02   0.     0.11   0.022  0.918 -0.743 -0.047  0.3  ]]
[[ 0.02   0.     0.11   0.022  0.918 -0.743 -0.047  0.299]]
[[ 0.02   0.     0.11   0.022  0.919 -0.743 -0.047  0.299]]
[[ 0.02   0.     0.11   0.022  0.92  -0.743 -0.047  0.299]]
[[ 0.02   0.     0.11   0.022  0.921 -0.743 -0.047  0.299]]
[[ 0.02   0.     0.11   0.022  0.921 -0.744 -0.047  0.299]]
[[ 0.02   0.     0.11   0.022  0.922 -0.744 -0.047  0.299]]
[[ 0.02   0.     0.11   0.022  0.923 -0.744 -0.047  0.299]]
[[ 0.02   0.     0.11   0.022  0.923 -0.745 -0.047  0.299]]
[[ 0.02   0.     0.11   0.022  0.924 -0.745 -0.047  0.299]]
[[ 0.02   0.     0.11   0.022  0.925 -0.745 -0.047  0.299]]
[[ 0.02   0.     0.11   0.022  0.925 -0.745 -0.047  0.298]]
[[ 0.02   0.     0.11   0.022  0.926 -0.745 -0.047  0.298]]
[[ 0.02   0.     0.11   0.022  0.927 -0.745 -0.047  0.298]]
[[ 0.02   0.     0.11   0.022  0.928 -0.745 -0.047  0.298]]
[[ 0.02   0.     0.11   0.022  0.929 -0.

[[ 0.023  0.     0.11   0.022  1.054 -0.769 -0.055  0.286]]
[[ 0.023  0.     0.11   0.022  1.055 -0.769 -0.055  0.286]]
[[ 0.023  0.     0.11   0.022  1.056 -0.769 -0.055  0.286]]
[[ 0.023  0.     0.11   0.022  1.056 -0.77  -0.055  0.286]]
[[ 0.023  0.     0.11   0.022  1.057 -0.77  -0.055  0.286]]
[[ 0.023  0.     0.11   0.022  1.058 -0.77  -0.055  0.286]]
[[ 0.023  0.     0.11   0.022  1.058 -0.77  -0.055  0.285]]
[[ 0.023  0.     0.11   0.022  1.059 -0.77  -0.055  0.285]]
[[ 0.023  0.     0.11   0.022  1.06  -0.77  -0.055  0.285]]
[[ 0.023  0.     0.11   0.022  1.061 -0.77  -0.055  0.285]]
[[ 0.023  0.     0.11   0.022  1.061 -0.771 -0.055  0.285]]
[[ 0.023  0.     0.11   0.022  1.062 -0.771 -0.055  0.285]]
[[ 0.023  0.     0.11   0.022  1.063 -0.771 -0.055  0.285]]
[[ 0.023  0.     0.11   0.022  1.064 -0.771 -0.055  0.285]]
[[ 0.023  0.     0.11   0.022  1.064 -0.772 -0.055  0.285]]
[[ 0.023  0.     0.11   0.022  1.065 -0.772 -0.055  0.285]]
[[ 0.023  0.     0.11   0.022  1.066 -0.

[[ 0.026  0.     0.11   0.022  1.188 -0.797 -0.061  0.272]]
[[ 0.026  0.     0.11   0.022  1.189 -0.797 -0.061  0.272]]
[[ 0.026  0.     0.11   0.022  1.19  -0.797 -0.061  0.272]]
[[ 0.026  0.     0.11   0.022  1.19  -0.797 -0.062  0.272]]
[[ 0.026  0.     0.11   0.022  1.191 -0.797 -0.062  0.272]]
[[ 0.026  0.     0.11   0.022  1.192 -0.797 -0.062  0.272]]
[[ 0.026  0.     0.11   0.022  1.193 -0.797 -0.062  0.272]]
[[ 0.026  0.     0.11   0.022  1.194 -0.797 -0.062  0.272]]
[[ 0.026  0.     0.11   0.022  1.194 -0.798 -0.062  0.272]]
[[ 0.026  0.     0.11   0.022  1.195 -0.798 -0.062  0.272]]
[[ 0.026  0.     0.11   0.022  1.196 -0.798 -0.062  0.272]]
[[ 0.026  0.     0.11   0.022  1.196 -0.799 -0.062  0.272]]
[[ 0.026  0.     0.11   0.022  1.197 -0.799 -0.062  0.272]]
[[ 0.026  0.     0.11   0.022  1.198 -0.799 -0.062  0.272]]
[[ 0.026  0.     0.11   0.022  1.199 -0.799 -0.062  0.272]]
[[ 0.026  0.     0.11   0.022  1.199 -0.799 -0.062  0.271]]
[[ 0.026  0.     0.11   0.022  1.2   -0.

[[ 0.029  0.     0.11   0.022  1.321 -0.823 -0.069  0.259]]
[[ 0.029  0.     0.11   0.022  1.322 -0.823 -0.069  0.259]]
[[ 0.029  0.     0.11   0.022  1.323 -0.823 -0.069  0.259]]
[[ 0.029  0.     0.11   0.022  1.324 -0.823 -0.069  0.259]]
[[ 0.029  0.     0.11   0.022  1.325 -0.823 -0.069  0.259]]
[[ 0.029  0.     0.11   0.022  1.325 -0.823 -0.069  0.258]]
[[ 0.029  0.     0.11   0.022  1.326 -0.823 -0.069  0.258]]
[[ 0.029  0.     0.11   0.022  1.327 -0.823 -0.069  0.258]]
[[ 0.029  0.     0.11   0.022  1.328 -0.823 -0.069  0.258]]
[[ 0.029  0.     0.11   0.022  1.328 -0.824 -0.069  0.258]]
[[ 0.029  0.     0.11   0.022  1.329 -0.824 -0.069  0.258]]
[[ 0.029  0.     0.11   0.022  1.33  -0.824 -0.069  0.258]]
[[ 0.029  0.     0.11   0.022  1.33  -0.825 -0.069  0.258]]
[[ 0.029  0.     0.11   0.022  1.331 -0.825 -0.069  0.258]]
[[ 0.029  0.     0.11   0.022  1.332 -0.825 -0.069  0.258]]
[[ 0.029  0.     0.11   0.022  1.333 -0.825 -0.069  0.258]]
[[ 0.029  0.     0.11   0.022  1.333 -0.

[[ 0.032  0.     0.111  0.022  1.453 -0.849 -0.076  0.245]]
[[ 0.032  0.     0.111  0.022  1.454 -0.849 -0.076  0.245]]
[[ 0.032  0.     0.111  0.022  1.454 -0.85  -0.076  0.245]]
[[ 0.032  0.     0.111  0.022  1.455 -0.85  -0.076  0.245]]
[[ 0.032  0.     0.111  0.022  1.456 -0.85  -0.076  0.245]]
[[ 0.032  0.     0.111  0.022  1.456 -0.851 -0.076  0.245]]
[[ 0.032  0.     0.111  0.022  1.457 -0.851 -0.076  0.245]]
[[ 0.032  0.     0.111  0.022  1.458 -0.851 -0.076  0.245]]
[[ 0.032  0.     0.111  0.022  1.459 -0.851 -0.076  0.245]]
[[ 0.032  0.     0.111  0.022  1.459 -0.851 -0.076  0.244]]
[[ 0.032  0.     0.111  0.022  1.46  -0.851 -0.076  0.244]]
[[ 0.032  0.     0.111  0.022  1.461 -0.851 -0.076  0.244]]
[[ 0.032  0.     0.111  0.022  1.462 -0.851 -0.076  0.244]]
[[ 0.032  0.     0.111  0.022  1.462 -0.852 -0.076  0.244]]
[[ 0.032  0.     0.111  0.022  1.463 -0.852 -0.076  0.244]]
[[ 0.032  0.     0.111  0.022  1.464 -0.852 -0.076  0.244]]
[[ 0.032  0.     0.111  0.022  1.464 -0.

[[ 0.034 -0.003  0.113  0.022  1.589 -0.876 -0.083  0.231]]
[[ 0.034 -0.003  0.113  0.022  1.59  -0.876 -0.083  0.231]]
[[ 0.034 -0.003  0.113  0.022  1.591 -0.876 -0.083  0.231]]
[[ 0.034 -0.003  0.113  0.022  1.592 -0.876 -0.083  0.231]]
[[ 0.034 -0.003  0.113  0.022  1.593 -0.876 -0.083  0.231]]
[[ 0.034 -0.003  0.113  0.022  1.593 -0.877 -0.083  0.231]]
[[ 0.034 -0.003  0.113  0.022  1.594 -0.877 -0.083  0.231]]
[[ 0.034 -0.003  0.113  0.022  1.595 -0.877 -0.083  0.231]]
[[ 0.034 -0.003  0.113  0.022  1.595 -0.878 -0.083  0.231]]
[[ 0.034 -0.003  0.113  0.022  1.596 -0.878 -0.083  0.231]]
[[ 0.034 -0.003  0.113  0.022  1.597 -0.878 -0.083  0.231]]
[[ 0.034 -0.003  0.113  0.022  1.597 -0.878 -0.083  0.23 ]]
[[ 0.034 -0.003  0.113  0.022  1.598 -0.878 -0.083  0.23 ]]
[[ 0.034 -0.003  0.113  0.022  1.599 -0.878 -0.083  0.23 ]]
[[ 0.034 -0.003  0.113  0.022  1.6   -0.878 -0.083  0.23 ]]
[[ 0.034 -0.003  0.113  0.022  1.6   -0.879 -0.083  0.23 ]]
[[ 0.034 -0.003  0.113  0.022  1.601 -0.

[[ 0.037 -0.004  0.114  0.022  1.721 -0.904 -0.089  0.218]]
[[ 0.037 -0.004  0.114  0.022  1.722 -0.904 -0.089  0.218]]
[[ 0.038 -0.004  0.114  0.022  1.722 -0.904 -0.089  0.218]]
[[ 0.038 -0.004  0.114  0.022  1.723 -0.904 -0.089  0.218]]
[[ 0.038 -0.004  0.114  0.022  1.723 -0.904 -0.09   0.218]]
[[ 0.038 -0.004  0.114  0.022  1.724 -0.904 -0.09   0.218]]
[[ 0.038 -0.004  0.114  0.022  1.725 -0.904 -0.09   0.218]]
[[ 0.038 -0.004  0.114  0.022  1.726 -0.904 -0.09   0.218]]
[[ 0.038 -0.004  0.114  0.022  1.727 -0.904 -0.09   0.218]]
[[ 0.038 -0.004  0.114  0.022  1.727 -0.904 -0.09   0.217]]
[[ 0.038 -0.004  0.114  0.022  1.728 -0.904 -0.09   0.217]]
[[ 0.038 -0.004  0.114  0.022  1.729 -0.904 -0.09   0.217]]
[[ 0.038 -0.004  0.114  0.022  1.73  -0.904 -0.09   0.217]]
[[ 0.038 -0.004  0.114  0.022  1.73  -0.905 -0.09   0.217]]
[[ 0.038 -0.004  0.114  0.022  1.731 -0.905 -0.09   0.217]]
[[ 0.038 -0.004  0.114  0.022  1.732 -0.905 -0.09   0.217]]
[[ 0.038 -0.004  0.114  0.022  1.732 -0.

[[ 0.04  -0.007  0.117  0.022  1.852 -0.929 -0.096  0.204]]
[[ 0.04  -0.007  0.117  0.022  1.852 -0.929 -0.097  0.204]]
[[ 0.04  -0.007  0.117  0.022  1.853 -0.929 -0.097  0.204]]
[[ 0.04  -0.007  0.117  0.022  1.854 -0.929 -0.097  0.204]]
[[ 0.04  -0.007  0.117  0.022  1.855 -0.929 -0.097  0.204]]
[[ 0.04  -0.007  0.117  0.022  1.856 -0.929 -0.097  0.204]]
[[ 0.04  -0.007  0.117  0.022  1.856 -0.93  -0.097  0.204]]
[[ 0.04  -0.007  0.117  0.022  1.857 -0.93  -0.097  0.204]]
[[ 0.04  -0.007  0.117  0.022  1.858 -0.93  -0.097  0.204]]
[[ 0.04  -0.007  0.117  0.022  1.858 -0.931 -0.097  0.204]]
[[ 0.04  -0.007  0.117  0.022  1.859 -0.931 -0.097  0.204]]
[[ 0.04  -0.007  0.117  0.022  1.86  -0.931 -0.097  0.204]]
[[ 0.04  -0.007  0.117  0.022  1.861 -0.931 -0.097  0.204]]
[[ 0.04  -0.007  0.117  0.022  1.861 -0.931 -0.097  0.203]]
[[ 0.04  -0.007  0.117  0.022  1.862 -0.931 -0.097  0.203]]
[[ 0.04  -0.007  0.117  0.022  1.863 -0.931 -0.097  0.203]]
[[ 0.04  -0.007  0.117  0.022  1.864 -0.

[[ 0.042 -0.008  0.118  0.022  1.986 -0.955 -0.104  0.19 ]]
[[ 0.042 -0.008  0.118  0.022  1.987 -0.955 -0.104  0.19 ]]
[[ 0.042 -0.008  0.118  0.022  1.988 -0.955 -0.104  0.19 ]]
[[ 0.042 -0.008  0.118  0.022  1.989 -0.955 -0.104  0.19 ]]
[[ 0.042 -0.008  0.118  0.022  1.989 -0.956 -0.104  0.19 ]]
[[ 0.042 -0.008  0.118  0.022  1.99  -0.956 -0.104  0.19 ]]
[[ 0.042 -0.008  0.118  0.022  1.991 -0.956 -0.104  0.19 ]]
[[ 0.043 -0.008  0.118  0.022  1.991 -0.956 -0.104  0.19 ]]
[[ 0.043 -0.008  0.118  0.022  1.992 -0.956 -0.104  0.19 ]]
[[ 0.043 -0.009  0.118  0.022  1.992 -0.956 -0.104  0.19 ]]
[[ 0.043 -0.009  0.119  0.022  1.992 -0.956 -0.104  0.19 ]]
[[ 0.043 -0.01   0.119  0.022  1.992 -0.956 -0.104  0.19 ]]
[[ 0.043 -0.01   0.119  0.022  1.993 -0.956 -0.104  0.19 ]]
[[ 0.043 -0.01   0.119  0.022  1.994 -0.956 -0.104  0.19 ]]
[[ 0.043 -0.01   0.119  0.022  1.995 -0.956 -0.104  0.19 ]]
[[ 0.043 -0.01   0.119  0.022  1.995 -0.956 -0.104  0.189]]
[[ 0.043 -0.01   0.119  0.022  1.996 -0.

[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.

[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.

[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.

[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.

[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.043 -0.011  0.12   0.022  2.023 -0.963 -0.105  0.187]]
[[ 0.044 -0.011  0.12   0.022  2.023 -0.

array([[ 0.   ,  0.   ,  0.   , ...,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   , ...,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   , ...,  0.   ,  0.   ,  0.   ],
       ..., 
       [ 0.043, -0.011,  0.12 , ..., -0.963, -0.105,  0.187],
       [ 0.044, -0.011,  0.12 , ..., -0.963, -0.105,  0.187],
       [ 0.043, -0.011,  0.12 , ..., -0.963, -0.105,  0.187]])